services:
  - type: web
    name: flask-salad-app
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://salad_db_user:w3jzOF64iZwcxSK6DekJzR77ctRmoCBd@dpg-d328peripnbc73d0ku50-a.singapore-postgres.render.com/salad_db
