services:
  - type: web
    name: flask-salad-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: mysaladdb
    plan: free
    databaseName: mysaladdb
    user: mysaladuser
